In [1]:
import sys
sys.path.append('/mnt/e/working/vietnamese_tts/melo')
from models import SynthesizerTrn, TextEncoder
from torch import nn
net_g = SynthesizerTrn(388,
1025,
32,
n_speakers=2,
mas_noise_scale_initial=0.01,
noise_scale_delta=2e-06,
**{'use_spk_conditioned_encoder': True, 'use_noise_scaled_mas': True, 'use_mel_posterior_encoder': False, 'use_duration_discriminator': True, 'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'n_layers_trans_flow': 3, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256})
net_g_enc_q = TextEncoder(
388,
192,
192,
768,
2,
6,
3,
0.1,
gin_channels=256,
num_languages=None,
num_tones=None,
)
emb_g = nn.Embedding(2, 256)

388
192
192
768
2
6
3
0.1
256
None
None


/home/giangtran/miniconda3/envs/melo_env/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [2]:
import torch
from torch.cuda.amp import autocast, GradScaler
x = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/x.pt", weights_only=True)
x_lengths = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/x_lengths.pt", weights_only=True)
spec = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/spec.pt", weights_only=True)
spec_lengths = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/spec_lengths.pt", weights_only=True)
speakers = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/speakers.pt", weights_only=True)
tone = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/tone.pt", weights_only=True)
language = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/language.pt", weights_only=True)
bert = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/bert.pt", weights_only=True)
ja_bert = torch.load("/mnt/e/working/vietnamese_tts/melo/tmp_test/ja_bert.pt", weights_only=True)
x = x.to("cpu")
x_lengths = x_lengths.to("cpu")
spec = spec.to("cpu")
spec_lengths = spec_lengths.to("cpu")
speakers = speakers.to("cpu")
tone = tone.to("cpu")
language = language.to("cpu")
bert = bert.to("cpu")
ja_bert = ja_bert.to("cpu")
net_g = net_g.to("cpu")
net_g_enc_q = net_g_enc_q.to("cpu")
emb_g = emb_g.to("cpu")
g = emb_g(speakers).unsqueeze(-1)

In [3]:
tone

tensor([[ 0, 14,  0, 14,  0, 15,  0, 14,  0, 14,  0, 14,  0, 14,  0, 15,  0, 14,
          0, 15,  0, 14,  0, 15,  0, 14,  0, 14,  0, 15,  0, 14,  0, 14,  0, 18,
          0, 14,  0, 16,  0, 14,  0, 14,  0, 19,  0, 14,  0, 14,  0]])

In [4]:
net_g_enc_q.emb(x)
net_g_enc_q.tone_emb(tone)
net_g_enc_q.language_emb(language)
bert_emb
ja_bert_emb
math.sqrt(
    self.hidden_channels
)

NameError: name 'bert_emb' is not defined

In [3]:
x, m_p, logs_p, x_mask = net_g_enc_q(
            x, x_lengths, tone, language, bert, ja_bert, g=g
        )

Dont get bert emb


IndexError: index out of range in self

In [3]:

net_g.train()
with autocast(enabled=False):
    (
        y_hat,
        l_length,
        attn,
        ids_slice,
        x_mask,
        z_mask,
        (z, z_p, m_p, logs_p, m_q, logs_q),
        (hidden_x, logw, logw_),
    ) = net_g(
        x,
        x_lengths,
        spec,
        spec_lengths,
        speakers,
        tone,
        language,
        bert,
        ja_bert,
    )

/tmp/ipykernel_22543/4062162224.py:2: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=False):


Done with spekers
Done do not use vc tensor([[[-4.1581e-01],
         [ 3.5135e-02],
         [ 2.5942e-01],
         [-4.0132e-01],
         [ 1.2945e+00],
         [ 8.9178e-01],
         [-1.0620e+00],
         [ 8.0340e-01],
         [ 4.1077e-01],
         [ 1.1019e+00],
         [ 8.7610e-01],
         [ 3.1375e-01],
         [-4.9503e-01],
         [ 4.3753e-01],
         [-5.0529e-01],
         [-4.3903e-01],
         [-5.1217e-01],
         [ 1.4721e+00],
         [-4.2399e-01],
         [-6.2359e-02],
         [ 1.8650e+00],
         [-2.3406e+00],
         [-5.1972e-01],
         [-5.1282e-01],
         [-9.5541e-01],
         [ 3.2500e-01],
         [ 4.9130e-02],
         [ 6.9914e-01],
         [ 1.2553e+00],
         [-6.9625e-01],
         [-4.1310e-02],
         [-2.1498e-01],
         [ 9.8868e-01],
         [ 7.8500e-01],
         [ 2.6427e-01],
         [-5.7853e-01],
         [-1.1451e-01],
         [ 6.1814e-01],
         [-7.8632e-01],
         [ 7.2646e-02],
   

IndexError: index out of range in self

In [ ]:
print(x)
print(x_lengths)
print(spec)
print(spec_lengths)
print(speakers)
print(tone)
print(language)
print(bert)
print(ja_bert)
print(net_g)

tensor([[  0,   0,   0, 137,   0, 253,   0, 116,   0, 318,   0, 182,   0, 116,
           0, 274,   0, 106,   0, 274,   0, 134,   0, 269,   0,  52,   0, 106,
           0, 250,   0, 114,   0, 242,   0, 263,   0, 182,   0, 270,   0, 104,
           0, 193,   0, 263,   0, 106,   0,   0,   0]])
tensor([51])
tensor([[[0.0010, 0.0010, 0.0010,  ..., 0.0010, 0.0010, 0.0010],
         [0.0010, 0.0010, 0.0010,  ..., 0.0010, 0.0010, 0.0010],
         [0.0010, 0.0010, 0.0010,  ..., 0.0010, 0.0010, 0.0010],
         ...,
         [0.0010, 0.0010, 0.0010,  ..., 0.0010, 0.0010, 0.0010],
         [0.0010, 0.0010, 0.0010,  ..., 0.0010, 0.0010, 0.0010],
         [0.0010, 0.0010, 0.0010,  ..., 0.0010, 0.0010, 0.0010]]])
tensor([226])
tensor([0])
tensor([[ 0, 14,  0, 14,  0, 15,  0, 14,  0, 14,  0, 14,  0, 14,  0, 15,  0, 14,
          0, 15,  0, 14,  0, 15,  0, 14,  0, 14,  0, 15,  0, 14,  0, 14,  0, 18,
          0, 14,  0, 16,  0, 14,  0, 14,  0, 19,  0, 14,  0, 14,  0]])
tensor([[0, 7, 0, 7, 0, 7, 0,

NameError: name 'net_g' is not defined